### ISSUE TITLE
bad error handling if nick in use

### ISSUE THREAD

**Issue by Akuli** [Akuli/irc-client#42]
Does not switch to new nick automatically. If you change nick manually, like `/nick foo`, you end up joining the channel but in a way where only others see that you joined, and you don't. Terminal full of errors:

```
Traceback (most recent call last):
  File "/home/akuli/irc-client/irc_client/backend.py", line 332, in _recv_loop
    self._handle_received_message(message)
  File "/home/akuli/irc-client/irc_client/backend.py", line 261, in _handle_received_message
    self._names_replys[channel].extend(
KeyError: '#a'
Traceback (most recent call last):
  File "/home/akuli/irc-client/irc_client/backend.py", line 332, in _recv_loop
    self._handle_received_message(message)
  File "/home/akuli/irc-client/irc_client/backend.py", line 268, in _handle_received_message
    nicks = self._names_replys.pop(channel)
KeyError: '#a'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/akuli/irc-client/irc_client/gui.py", line 489, in handle_events
    assert channel_view is not None
AssertionError
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/akuli/irc-client/irc_client/gui.py", line 494, in handle_events
    assert channel_view is not None
AssertionError
Traceback (most recent call last):
  File "/home/akuli/irc-client/irc_client/backend.py", line 332, in _recv_loop
    self._handle_received_message(message)
  File "/home/akuli/irc-client/irc_client/backend.py", line 261, in _handle_received_message
    self._names_replys[channel].extend(
KeyError: '#a'
Traceback (most recent call last):
  File "/home/akuli/irc-client/irc_client/backend.py", line 332, in _recv_loop
    self._handle_received_message(message)
  File "/home/akuli/irc-client/irc_client/backend.py", line 268, in _handle_received_message
    nicks = self._names_replys.pop(channel)
KeyError: '#a'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 749, in callit
    func(*args)
  File "/home/akuli/irc-client/irc_client/gui.py", line 489, in handle_events
    assert channel_view is not None
AssertionError
```

**Comment by Akuli** [comment]
Reconnecting to libera, with old nick ghosted, I get a bunch of output including this:

```
[23:44] mercury.libera.chat | 433 * Akuli Nickname is already in use.
```

Apparently 433 nickname already used, and it would be possible to just respond to it with another `NICK` command.
